name: Build and Push to Quay.io

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Quay.io
      env:
        QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      run: |
        echo "$QUAY_PASSWORD" | podman login quay.io -u "$QUAY_USERNAME" --password-stdin

    - name: Build image with Podman
      run: podman build -t quay.io/${{ secrets.QUAY_USERNAME }}/react-todo-app:latest .

    - name: Push image to Quay.io
      run: podman push quay.io/${{ secrets.QUAY_USERNAME }}/react-todo-app:latest
