name: Push Existing Image to Quay.io

on:
  push:
    branches:
      - main

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Quay.io
      env:
        QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      run: |
        echo "$QUAY_PASSWORD" | podman login quay.io -u "$QUAY_USERNAME" --password-stdin

    - name: Push image to Quay.io
      run: |
        TAG=latest
        podman push quay.io/${{ secrets.QUAY_USERNAME }}/react-todo-app:$TAG
